class MenuSeedData {
  static final Map<String, List<Map<String, dynamic>>> restaurantMenus = {
    'Spice Villa': [
      {
        'item_name': 'Paneer Butter Masala',
        'price': 160.0,
        'photo_url': 'assets/Menu/Paneer.png',
        'chef_special': 1,
        'category': 'Main Course',
        'description': 'Creamy tomato-based curry with paneer',
      },
      {
        'item_name': 'Butter Naan',
        'price': 45.0,
        'photo_url': 'assets/Menu/Naan.png',
        'chef_special': 0,
        'category': 'Breads',
        'description': 'Soft buttery Indian bread',
      },
      {
        'item_name': 'Jeera Rice',
        'price': 85.0,
        'photo_url': 'assets/Menu/jeera.png',
        'chef_special': 0,
        'category': 'Rice',
        'description': 'Fragrant basmati rice with cumin',
      },
    ],
    'Tasty Treat': [
      {
        'item_name': 'Chocolate Lava Cake',
        'price': 120.0,
        'photo_url': 'assets/Menu/lava.png',
        'chef_special': 1,
        'category': 'Desserts',
        'description': 'Warm chocolate cake with molten center',
      },
      {
        'item_name': 'French Fries',
        'price': 60.0,
        'photo_url': 'assets/Menu/fries.png',
        'chef_special': 0,
        'category': 'Snacks',
        'description': 'Crispy golden fries',
      },
      {
        'item_name': 'Cold Coffee',
        'price': 80.0,
        'photo_url': 'assets/Menu/coffee.png',
        'chef_special': 0,
        'category': 'Beverages',
        'description': 'Chilled coffee with ice cream',
      },
    ],
    'North Feast': [
      {
        'item_name': 'Punjabi Thali',
        'price': 200.0,
        'photo_url': 'assets/Menu/thali.png',
        'chef_special': 1,
        'category': 'Thali',
        'description': 'Complete Punjabi meal platter',
      },
      {
        'item_name': 'Makki di Roti',
        'price': 40.0,
        'photo_url': 'assets/Menu/makki.png',
        'chef_special': 0,
        'category': 'Breads',
        'description': 'Traditional corn flatbread',
      },
      {
        'item_name': 'Sarson da Saag',
        'price': 120.0,
        'photo_url': 'assets/Menu/sarson.png',
        'chef_special': 0,
        'category': 'Main Course',
        'description': 'Mustard greens curry',
      },
    ],
    'Urban Chops': [
      {
        'item_name': 'Grilled Chicken',
        'price': 300.0,
        'photo_url': 'https://images.unsplash.com/photo-1555992336-03a23c0b9c01?auto=format&fit=crop&w=100&q=80',
        'chef_special': 1,
        'category': 'Main Course',
        'description': 'Perfectly grilled chicken breast',
      },
      {
        'item_name': 'French Mashed Potatoes',
        'price': 120.0,
        'photo_url': 'assets/Menu/chicken g.jpeg',
        'chef_special': 0,
        'category': 'Sides',
        'description': 'Creamy mashed potatoes',
      },
      {
        'item_name': 'Caesar Salad',
        'price': 150.0,
        'photo_url': 'assets/Menu/ceaser.jpeg',
        'chef_special': 0,
        'category': 'Salads',
        'description': 'Fresh romaine with Caesar dressing',
      },
    ],
    'The Bombay Plate': [
      {
        'item_name': 'Vada Pav',
        'price': 70.0,
        'photo_url': 'assets/Menu/vadapav.jpeg',
        'chef_special': 1,
        'category': 'Street Food',
        'description': 'Mumbai\'s iconic street food',
      },
      {
        'item_name': 'Pav Bhaji',
        'price': 120.0,
        'photo_url': 'assets/Menu/pav bhaji.jpeg',
        'chef_special': 0,
        'category': 'Street Food',
        'description': 'Spicy vegetable curry with bread',
      },
      {
        'item_name': 'Misal Pav',
        'price': 110.0,
        'photo_url': 'assets/Menu/misal.jpeg',
        'chef_special': 0,
        'category': 'Street Food',
        'description': 'Spicy sprouted lentils curry',
      },
    ],
    'Coastal Curry': [
      {
        'item_name': 'Fish Curry',
        'price': 350.0,
        'photo_url': 'assets/Menu/fish.jpeg',
        'chef_special': 1,
        'category': 'Seafood',
        'description': 'Fresh fish in coconut curry',
      },
      {
        'item_name': 'Appam',
        'price': 60.0,
        'photo_url': 'assets/Menu/appam.jpeg',
        'chef_special': 0,
        'category': 'Breads',
        'description': 'Soft rice pancakes',
      },
      {
        'item_name': 'Prawn Fry',
        'price': 300.0,
        'photo_url': 'assets/Menu/prawn.jpeg',
        'chef_special': 0,
        'category': 'Seafood',
        'description': 'Crispy fried prawns',
      },
    ],
    'Pizza Powerhouse': [
      {
        'item_name': 'Margherita Pizza',
        'price': 250.0,
        'photo_url': 'assets/Menu/margherita.jpeg',
        'chef_special': 1,
        'category': 'Pizza',
        'description': 'Classic tomato and mozzarella',
      },
      {
        'item_name': 'Garlic Bread',
        'price': 90.0,
        'photo_url': 'assets/Menu/garlic bread.jpeg',
        'chef_special': 0,
        'category': 'Appetizers',
        'description': 'Toasted bread with garlic butter',
      },
      {
        'item_name': 'Peppy Paneer Pizza',
        'price': 280.0,
        'photo_url': 'assets/Menu/aneer piza.jpeg',
        'chef_special': 0,
        'category': 'Pizza',
        'description': 'Spicy paneer with peppers',
      },
    ],
  };
}
